# Generated by Django 2.0 on 2021-09-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20210917_2035'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='message',
        #     name='image',
        #     field=models.ImageField(blank=True, null=True, upload_to='msjs', verbose_name='Adjunto'),
        # ),
    ]
